[package]
name = "nordc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }
logos = "0.13.0"

[build-dependencies]
lalrpop = "0.20.0"
